import { PublicClient, createPublicClient, http } from "viem";
import {
  Chain,
  arbitrum,
  arbitrumGoerli,
  arbitrumNova,
  avalanche,
  avalancheFuji,
  base,
  baseGoerli,
  boba,
  bsc,
  bscTestnet,
  canto,
  celo,
  celoAlfajores,
  celoCannoli,
  fantom,
  fantomTestnet,
  gnosis,
  gnosisChiado,
  goerli,
  linea,
  lineaTestnet,
  mainnet,
  mantle,
  mantleTestnet,
  metis,
  metisGoerli,
  opBNB,
  opBNBTestnet,
  optimism,
  optimismGoerli,
  polygon,
  polygonMumbai,
  polygonZkEvm,
  polygonZkEvmTestnet,
  sepolia,
  zkSync,
  zkSyncTestnet,
  zora,
  zoraTestnet,
} from "viem/chains";

export const chains: Chain[] = [
  mainnet,
  goerli,
  sepolia,
  arbitrum,
  arbitrumGoerli,
  arbitrumNova,
  optimism,
  optimismGoerli,
  polygon,
  polygonMumbai,
  polygonZkEvm,
  polygonZkEvmTestnet,
  base,
  baseGoerli,
  avalanche,
  avalancheFuji,
  boba,
  bsc,
  bscTestnet,
  canto,
  celo,
  celoAlfajores,
  celoCannoli,
  fantom,
  fantomTestnet,
  gnosis,
  gnosisChiado,
  linea,
  lineaTestnet,
  mantle,
  mantleTestnet,
  metis,
  metisGoerli,
  opBNB,
  opBNBTestnet,
  zkSync,
  zkSyncTestnet,
  zora,
  zoraTestnet,
];

export const mainnetClient: PublicClient = createPublicClient({
  chain: mainnet,
  transport: http(),
});

export const clients: PublicClient[] = chains.map((chain) =>
  createPublicClient({ chain, transport: http() })
);
